name: gh-deploy

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Setup-node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      -
        run: |
          npm i axios
          npm run fetch
      -
        name: Commit latest github data
        uses: EndBug/add-and-commit@v5
        with: 
          add: 'data'
          message: 'Latest github data update for ${{ env.GITHUB_RUN_ID }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_GHTOKEN: ${{ secrets.ACCESS_TOKEN }} 
      -
        name: Build project
        uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: release
      