name: gh-deploy

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build project
        uses: enriikke/gatsby-gh-pages-action@v2
        with:
          skip-publish: true