name: gh-test

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2-beta

      -
        name: Test build project
        run: |
          npm install
          npm run build
