name: gh-deploy

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build project
        uses: actions/setup-node@v2-beta
        run: |
          npm install
          npm run release